version: '3'

services:
  mysql:
    build: ./docker/mysql
    hostname: httpd
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
  apache:
    build: .
    hostname: ServerApache
    volumes:
      - ./public_html/:/var/www/html/
    ports:
      - "8080:80"
  php:
    build: ./docker/php
    volumes:
      - ./public_html/:/var/www/html/
