version: '3'

services:
  mysql:
    container_name: mysql
    build: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
            MYSQL_ROOT_PASSWORD: hello
    volumes:
      - ./docker/mysql/db_file:/var/lib/mysql
    networks:
      - networkName
  apache:
    build: ./docker/apache
    volumes:
      - ./public_html/:/var/www/localhost/htdocs/
    ports:
      - "8080:80"
    depends_on:
      - mysql
  phpmyadmin:
      image: phpmyadmin:5.1-apache
      container_name: phpmyadmin
      depends_on: 
      - mysql
      environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      restart: always
      ports:
      - 8090:80
      links: 
      - "mysql"
      networks:
      - networkName
networks:
  networkName:
    name: networkName