version: '3'

services:
  mysql:
    container_name: mysql
    build: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
            MYSQL_ROOT_PASSWORD: hello
    volumes:
      - ./docker/mysql/db_file:/var/lib/mysql
    networks:
      - networkName
  apache:
    build: ./docker/apache
    volumes:
      - ./public_html/:/var/www/localhost/htdocs/
    ports:
      - "8080:80"
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8090:80'
    restart: always
    environment:
        PMA_HOST: mysql
    depends_on:
        - mysql
    networks:
      - networkName
networks:
  networkName:
    name: networkName