version: '3'

services:
  mysql:
    container_name: php-apache
    build: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - .:/app
    networks:
      - backend
  apache:
    build: ./docker/apache
    volumes:
      - ./public_html/:/var/www/localhost/htdocs/
    ports:
      - "8080:80"
    networks:
      - backend
  php:
    build: ./docker/php
    volumes:
      - ./public_html/:/var/www/html/
networks:
      - backend